services:
  server:
    # container_name: sdcc-server-composed
    build: https://github.com/gmarseglia/SDCC-Server.git
    environment:
      - ParallelWorkers=4
      - ReplicationGrade=2
    entrypoint: server
    networks:
      net:
        ipv4_address: 192.170.0.2

  worker1:
    # container_name: sdcc-worker-composed
    build: https://github.com/gmarseglia/SDCC-Worker.git
    environment:
      - MasterAddr=192.170.0.2
      - HostAddr=192.170.0.3
      - HostPort=0
    entrypoint: worker
    depends_on:
      - server
    networks:
      net:
        ipv4_address: 192.170.0.3

  worker2:
    # container_name: sdcc-worker-composed
    build: https://github.com/gmarseglia/SDCC-Worker.git
    environment:
      - MasterAddr=192.170.0.2
      - HostAddr=192.170.0.4
      - HostPort=0
    entrypoint: worker
    depends_on:
      - server
    networks:
      net:
        ipv4_address: 192.170.0.4

  worker3:
    # container_name: sdcc-worker-composed
    build: https://github.com/gmarseglia/SDCC-Worker.git
    environment:
      - MasterAddr=192.170.0.2
      - HostAddr=192.170.0.5
      - HostPort=0
    entrypoint: worker
    depends_on:
      - server
    networks:
      net:
        ipv4_address: 192.170.0.5

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "192.170.0.0/24"
